PRICE_UNIT_GROUPS = [
    {
        "label": "Weight / Mass",
        "units": [
            {"code": "oz", "abbrev": "oz", "label": "per ounce (oz)"},
            {"code": "lb", "abbrev": "lb", "label": "per pound (lb)"},
            {"code": "g", "abbrev": "g", "label": "per gram (g)"},
            {"code": "100g", "abbrev": "100g",
                "label": "per 100 grams (100g)"},
            {"code": "kg", "abbrev": "kg", "label": "per kilogram (kg)"},
            {"code": "t", "abbrev": "t", "label": "per metric ton (t)"},
        ],
    },
    {
        "label": "Volume",
        "units": [
            {"code": "floz", "abbrev": "fl oz",
                "label": "per fluid ounce (fl oz)"},
            {"code": "ml", "abbrev": "mL", "label": "per milliliter (mL)"},
            {"code": "100ml", "abbrev": "100mL",
                "label": "per 100 milliliters (100mL)"},
            {"code": "pt", "abbrev": "pt", "label": "per pint (pt)"},
            {"code": "qt", "abbrev": "qt", "label": "per quart (qt)"},
            {"code": "gal", "abbrev": "gal", "label": "per gallon (gal)"},
            {"code": "l", "abbrev": "L", "label": "per liter (L)"},
        ],
    },
    {
        "label": "Count",
        "units": [
            {"code": "ct", "abbrev": "ct", "label": "per count (ct)"},
            {"code": "ea", "abbrev": "ea", "label": "per each (ea)"},
            {"code": "pc", "abbrev": "pc", "label": "per piece (pc)"},
            {"code": "pk", "abbrev": "pk", "label": "per pack (pk)"},
            {"code": "dz", "abbrev": "dz", "label": "per dozen (dz)"},
            {"code": "sheet", "abbrev": "sheet", "label": "per sheet (sheet)"},
            {"code": "cap", "abbrev": "cap", "label": "per capsule (cap)"},
            {"code": "tab", "abbrev": "tab", "label": "per tablet (tab)"},
            {"code": "dose", "abbrev": "dose", "label": "per dose (dose)"},
            {"code": "serving", "abbrev": "serving",
                "label": "per serving (serving)"},
            {"code": "unit", "abbrev": "unit", "label": "per unit (unit)"},
        ],
    },
    {
        "label": "Length / Distance",
        "units": [
            {"code": "in", "abbrev": "in", "label": "per inch (in)"},
            {"code": "ft", "abbrev": "ft", "label": "per foot (ft)"},
            {"code": "yd", "abbrev": "yd", "label": "per yard (yd)"},
            {"code": "mm", "abbrev": "mm", "label": "per millimeter (mm)"},
            {"code": "cm", "abbrev": "cm", "label": "per centimeter (cm)"},
            {"code": "m", "abbrev": "m", "label": "per meter (m)"},
        ],
    },
    {
        "label": "Area",
        "units": [
            {"code": "sqin", "abbrev": "sq in",
                "label": "per square inch (sq in)"},
            {"code": "sqft", "abbrev": "sq ft",
                "label": "per square foot (sq ft)"},
            {"code": "sqyd", "abbrev": "sq yd",
                "label": "per square yard (sq yd)"},
            {"code": "sqcm", "abbrev": "sq cm",
                "label": "per square centimeter (sq cm)"},
            {"code": "sqm", "abbrev": "sq m",
                "label": "per square meter (sq m)"},
        ],
    },
]
